version: '3.7'

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    hostname: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passwd@123

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    hostname: mongo-express
    ports:
      - 8881:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: passwd@123

  webapp:
    container_name: webapp
    build:
      dockerfile: Dockerfile
      context: ./
    restart: always
    hostname: webapp